/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppInvestmentsIndexRouteImport } from './routes/app/investments/index'
import { Route as AppEmisIndexRouteImport } from './routes/app/emis/index'
import { Route as AppActivityIndexRouteImport } from './routes/app/activity/index'
import { Route as AppInvestmentsNewRouteImport } from './routes/app/investments/new'
import { Route as AppEmisNewRouteImport } from './routes/app/emis/new'
import { Route as AppEmisEmiIdRouteImport } from './routes/app/emis/$emiId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppInvestmentsSavingsNewRouteImport } from './routes/app/investments/savings/new'
import { Route as AppInvestmentsSavingsIdRouteImport } from './routes/app/investments/savings/$id'
import { Route as AppInvestmentsDpsNewRouteImport } from './routes/app/investments/dps/new'
import { Route as AppInvestmentsDpsIdRouteImport } from './routes/app/investments/dps/$id'
import { Route as AppInvestmentsIdEditRouteImport } from './routes/app/investments/$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvestmentsIndexRoute = AppInvestmentsIndexRouteImport.update({
  id: '/investments/',
  path: '/investments/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmisIndexRoute = AppEmisIndexRouteImport.update({
  id: '/emis/',
  path: '/emis/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityIndexRoute = AppActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvestmentsNewRoute = AppInvestmentsNewRouteImport.update({
  id: '/investments/new',
  path: '/investments/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmisNewRoute = AppEmisNewRouteImport.update({
  id: '/emis/new',
  path: '/emis/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmisEmiIdRoute = AppEmisEmiIdRouteImport.update({
  id: '/emis/$emiId',
  path: '/emis/$emiId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvestmentsSavingsNewRoute =
  AppInvestmentsSavingsNewRouteImport.update({
    id: '/investments/savings/new',
    path: '/investments/savings/new',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInvestmentsSavingsIdRoute = AppInvestmentsSavingsIdRouteImport.update({
  id: '/investments/savings/$id',
  path: '/investments/savings/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvestmentsDpsNewRoute = AppInvestmentsDpsNewRouteImport.update({
  id: '/investments/dps/new',
  path: '/investments/dps/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvestmentsDpsIdRoute = AppInvestmentsDpsIdRouteImport.update({
  id: '/investments/dps/$id',
  path: '/investments/dps/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvestmentsIdEditRoute = AppInvestmentsIdEditRouteImport.update({
  id: '/investments/$id/edit',
  path: '/investments/$id/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/emis/$emiId': typeof AppEmisEmiIdRoute
  '/app/emis/new': typeof AppEmisNewRoute
  '/app/investments/new': typeof AppInvestmentsNewRoute
  '/app/activity/': typeof AppActivityIndexRoute
  '/app/emis/': typeof AppEmisIndexRoute
  '/app/investments/': typeof AppInvestmentsIndexRoute
  '/app/investments/$id/edit': typeof AppInvestmentsIdEditRoute
  '/app/investments/dps/$id': typeof AppInvestmentsDpsIdRoute
  '/app/investments/dps/new': typeof AppInvestmentsDpsNewRoute
  '/app/investments/savings/$id': typeof AppInvestmentsSavingsIdRoute
  '/app/investments/savings/new': typeof AppInvestmentsSavingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/emis/$emiId': typeof AppEmisEmiIdRoute
  '/app/emis/new': typeof AppEmisNewRoute
  '/app/investments/new': typeof AppInvestmentsNewRoute
  '/app/activity': typeof AppActivityIndexRoute
  '/app/emis': typeof AppEmisIndexRoute
  '/app/investments': typeof AppInvestmentsIndexRoute
  '/app/investments/$id/edit': typeof AppInvestmentsIdEditRoute
  '/app/investments/dps/$id': typeof AppInvestmentsDpsIdRoute
  '/app/investments/dps/new': typeof AppInvestmentsDpsNewRoute
  '/app/investments/savings/$id': typeof AppInvestmentsSavingsIdRoute
  '/app/investments/savings/new': typeof AppInvestmentsSavingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/emis/$emiId': typeof AppEmisEmiIdRoute
  '/app/emis/new': typeof AppEmisNewRoute
  '/app/investments/new': typeof AppInvestmentsNewRoute
  '/app/activity/': typeof AppActivityIndexRoute
  '/app/emis/': typeof AppEmisIndexRoute
  '/app/investments/': typeof AppInvestmentsIndexRoute
  '/app/investments/$id/edit': typeof AppInvestmentsIdEditRoute
  '/app/investments/dps/$id': typeof AppInvestmentsDpsIdRoute
  '/app/investments/dps/new': typeof AppInvestmentsDpsNewRoute
  '/app/investments/savings/$id': typeof AppInvestmentsSavingsIdRoute
  '/app/investments/savings/new': typeof AppInvestmentsSavingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/profile'
    | '/app/'
    | '/api/auth/$'
    | '/app/emis/$emiId'
    | '/app/emis/new'
    | '/app/investments/new'
    | '/app/activity/'
    | '/app/emis/'
    | '/app/investments/'
    | '/app/investments/$id/edit'
    | '/app/investments/dps/$id'
    | '/app/investments/dps/new'
    | '/app/investments/savings/$id'
    | '/app/investments/savings/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/profile'
    | '/app'
    | '/api/auth/$'
    | '/app/emis/$emiId'
    | '/app/emis/new'
    | '/app/investments/new'
    | '/app/activity'
    | '/app/emis'
    | '/app/investments'
    | '/app/investments/$id/edit'
    | '/app/investments/dps/$id'
    | '/app/investments/dps/new'
    | '/app/investments/savings/$id'
    | '/app/investments/savings/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/profile'
    | '/app/'
    | '/api/auth/$'
    | '/app/emis/$emiId'
    | '/app/emis/new'
    | '/app/investments/new'
    | '/app/activity/'
    | '/app/emis/'
    | '/app/investments/'
    | '/app/investments/$id/edit'
    | '/app/investments/dps/$id'
    | '/app/investments/dps/new'
    | '/app/investments/savings/$id'
    | '/app/investments/savings/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/investments/': {
      id: '/app/investments/'
      path: '/investments'
      fullPath: '/app/investments/'
      preLoaderRoute: typeof AppInvestmentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/emis/': {
      id: '/app/emis/'
      path: '/emis'
      fullPath: '/app/emis/'
      preLoaderRoute: typeof AppEmisIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/activity/': {
      id: '/app/activity/'
      path: '/activity'
      fullPath: '/app/activity/'
      preLoaderRoute: typeof AppActivityIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/investments/new': {
      id: '/app/investments/new'
      path: '/investments/new'
      fullPath: '/app/investments/new'
      preLoaderRoute: typeof AppInvestmentsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/emis/new': {
      id: '/app/emis/new'
      path: '/emis/new'
      fullPath: '/app/emis/new'
      preLoaderRoute: typeof AppEmisNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/emis/$emiId': {
      id: '/app/emis/$emiId'
      path: '/emis/$emiId'
      fullPath: '/app/emis/$emiId'
      preLoaderRoute: typeof AppEmisEmiIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/investments/savings/new': {
      id: '/app/investments/savings/new'
      path: '/investments/savings/new'
      fullPath: '/app/investments/savings/new'
      preLoaderRoute: typeof AppInvestmentsSavingsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/investments/savings/$id': {
      id: '/app/investments/savings/$id'
      path: '/investments/savings/$id'
      fullPath: '/app/investments/savings/$id'
      preLoaderRoute: typeof AppInvestmentsSavingsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/investments/dps/new': {
      id: '/app/investments/dps/new'
      path: '/investments/dps/new'
      fullPath: '/app/investments/dps/new'
      preLoaderRoute: typeof AppInvestmentsDpsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/investments/dps/$id': {
      id: '/app/investments/dps/$id'
      path: '/investments/dps/$id'
      fullPath: '/app/investments/dps/$id'
      preLoaderRoute: typeof AppInvestmentsDpsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/investments/$id/edit': {
      id: '/app/investments/$id/edit'
      path: '/investments/$id/edit'
      fullPath: '/app/investments/$id/edit'
      preLoaderRoute: typeof AppInvestmentsIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmisEmiIdRoute: typeof AppEmisEmiIdRoute
  AppEmisNewRoute: typeof AppEmisNewRoute
  AppInvestmentsNewRoute: typeof AppInvestmentsNewRoute
  AppActivityIndexRoute: typeof AppActivityIndexRoute
  AppEmisIndexRoute: typeof AppEmisIndexRoute
  AppInvestmentsIndexRoute: typeof AppInvestmentsIndexRoute
  AppInvestmentsIdEditRoute: typeof AppInvestmentsIdEditRoute
  AppInvestmentsDpsIdRoute: typeof AppInvestmentsDpsIdRoute
  AppInvestmentsDpsNewRoute: typeof AppInvestmentsDpsNewRoute
  AppInvestmentsSavingsIdRoute: typeof AppInvestmentsSavingsIdRoute
  AppInvestmentsSavingsNewRoute: typeof AppInvestmentsSavingsNewRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmisEmiIdRoute: AppEmisEmiIdRoute,
  AppEmisNewRoute: AppEmisNewRoute,
  AppInvestmentsNewRoute: AppInvestmentsNewRoute,
  AppActivityIndexRoute: AppActivityIndexRoute,
  AppEmisIndexRoute: AppEmisIndexRoute,
  AppInvestmentsIndexRoute: AppInvestmentsIndexRoute,
  AppInvestmentsIdEditRoute: AppInvestmentsIdEditRoute,
  AppInvestmentsDpsIdRoute: AppInvestmentsDpsIdRoute,
  AppInvestmentsDpsNewRoute: AppInvestmentsDpsNewRoute,
  AppInvestmentsSavingsIdRoute: AppInvestmentsSavingsIdRoute,
  AppInvestmentsSavingsNewRoute: AppInvestmentsSavingsNewRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
